language: php

matrix:
  include:
    - php: 8.0
      dist: bionic
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi